declare const _sfc_main: import("vue").DefineComponent<{}, {
    test1: import("vue").Ref<string>;
    handleInput1: (val: any) => void;
    test2: import("vue").Ref<string>;
    handleInput2: (val: any) => void;
    test3: import("vue").Ref<string>;
    handleInput3: (val: any) => void;
    test4: import("vue").Ref<string>;
    temp: import("vue").Ref<string>;
    handleInput4: (val: any) => void;
    test5: import("vue").Ref<string>;
    handleInput5: (val: any) => void;
    handleFocus: (val: any) => void;
    handleBlur: (val: any) => void;
    test6: import("vue").Ref<string>;
    handleInput6: (val: any) => void;
    test7: import("vue").Ref<string>;
    handleInput7: (val: any) => void;
    code1: string;
    code2: string;
    code3: string;
    code4: string;
    code5: string;
    code6: string;
    code7: string;
}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{}>>, {}>;
export default _sfc_main;
